name: Build and deploy Java project to Azure Function App - webapp-f

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: webapp-f # Azure Function App name
  PACKAGE_DIRECTORY: '.' # Directory containing pom.xml
  JAVA_VERSION: '11' # Java version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Java SDK ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Restore Project Dependencies & Build'
        run: |
          cd ${{ env.PACKAGE_DIRECTORY }}
          mvn clean package

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_566A4A64F6DD46FC9B598A0E60160060 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E0730AEEB2974EB1A498E9DEF234BB66 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D3AF730F67B84009952A9A056E9DE34C }}

      - name: 'Deploy to Azure Function App'
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_DIRECTORY }}
          respect-pom-xml: true
